# Generated by Django 4.2.16 on 2024-09-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField()),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_photo', models.ImageField(default='dd', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
